[package]
name = "round5-rs"
version = "0.1.0"
authors = ["Jack Lloyd <jack.lloyd@fortanix.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keccak = "0.1"
